### ISSUE TITLE
Can't build with vcpkg linux.

### ISSUE THREAD

**Issue by 2403772980ygy** [alembic/alembic#285]
I tried to use vcpkg to install this on Linux, however, it failed with this error in the logs:

```log
/d/vcpkg/installed/x64-linux/include/OpenEXR/half.h:515:10: error: implicitly-declared ‘constexpr half::half(const half&)’ is deprecated [-Werror=deprecated-copy]
```
this appeared in the logs for multiple times and in multiple lines.

I guess that I should report this here and not the vcpkg repository.

What's wrong with my build and what can I do to solve this?

Linux: manjaro KDE, basically arch linux.

**Comment by lamiller0** [comment]
What gcc and which version of OpenEXR?

**Comment by simogasp** [comment]
this should be related to #263

**Comment by simogasp** [comment]
(and potentially fixed by #268)

**Comment by 2403772980ygy** [comment]
It's GCC 10 and is latest openEXR

**Comment by 2403772980ygy** [comment]
So it should work after #268 is merged and the vcpkg port is updated, right?

**Comment by lamiller0** [comment]
Please try it with 1.7.13 and report back if its still broken.

**Comment by 2403772980ygy** [comment]
OK, thanks. I'll give a try now
